    res_graph_2[regions].SetMarkerSize(1.2)
    res_graph_2[regions].SetMarkerStyle(21)
    res_graph_2[regions].SetLineColor(ROOT.kRed)
    res_graph_2[regions].SetMarkerColor(ROOT.kRed)
    res_graph_2[regions].GetXaxis().SetTitleSize(0.042)
    res_graph_2[regions].GetXaxis().SetTitle('m_{ee} [GeV]')
    res_graph_2[regions].GetYaxis().SetTitleSize(0.052)
    res_graph_2[regions].GetYaxis().SetTitle('#sigma_{fit}')
